from JLAB import *

motorL = MotorSimGIF(-80, 0)
motorR = MotorSimGIF(80, 0)

s_switch = Switch(0, 0)  
i=1
while True:

    if s_switch.read()==1:
        
        if i==1:
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)    
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.5)     #한바퀴
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)    
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.5)     #두바퀴

            motorL.write(0, 1)  # 왼쪽 모터 켜고, 오른쪽 모터 정지
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            i=2
            print("r1")

        elif i==2:
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)    
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.5)     #한바퀴
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)    
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.5)     #두바퀴
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)    
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.1)
            motorL.write(0, 1)
            motorR.write(1, 0)
            time.sleep(0.5)     #세바퀴

            motorL.write(0, 1)  # 왼쪽 모터 켜고, 오른쪽 모터 정지
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            motorL.write(0, 1)
            time.sleep(0.1)
            motorL.write(0,1)
            time.sleep(0.1)
            i=1
            print("r2")
    

        else:
            print("error")
            
    else:
        print("waiting comand...")
        motorL.write(0, 0)
        motorR.write(0, 0)
    